package com.example.docconnect;

/**
 * Data model representing a clinic image stored in Cloudinary with metadata in Firebase.
 * This class is designed to be compatible with Firebase Realtime Database's
 * data mapping (deserialization).
 */
public class ClinicImageModel {

    // The unique identifier generated by Firebase's .push() method
    private String key;

    // The hosted web link (URL) where the image is stored on Cloudinary
    private String url;

    /**
     * Required empty constructor for Firebase Realtime Database.
     * Firebase needs this to create an instance of the class before
     * populating the fields with data from the database snapshot.
     */
    public ClinicImageModel() {
    }

    /**
     * Parameterized constructor to manually create a model instance.
     * @param key The Firebase push ID associated with this image entry.
     * @param url The public URL provided by Cloudinary after a successful upload.
     */
    public ClinicImageModel(String key, String url) {
        this.key = key;
        this.url = url;
    }

    /**
     * @return The unique Firebase key used to identify this specific database node.
     */
    public String getKey() {
        return key;
    }

    /**
     * @param key Sets the Firebase key for this model instance.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * @return The absolute URL string pointing to the image file.
     */
    public String getUrl() {
        return url;
    }

    /**
     * @param url Sets the web URL for this model instance.
     */
    public void setUrl(String url) {
        this.url = url;
    }
}