package com.example.docconnect;

/**
 * Model class representing a support or bug report ticket.
 * Stores technical metadata alongside user descriptions to assist in debugging.
 */
public class SupportTicket {

    // Unique identifier for the ticket (usually generated by Firebase push())
    public String ticketId;

    // Name of the doctor/user reporting the issue
    public String doctorName;

    // The type of issue (e.g., "Technical", "Billing", "Account Access")
    public String category;

    // Detailed user description of the problem
    public String description;

    // System metadata for debugging
    public String deviceModel;      // e.g., "Samsung Galaxy S21"
    public String androidVersion;   // e.g., "Android 13"
    public String appVersion;       // e.g., "1.0.4"

    // Optional screenshot or log file URL stored in Firebase Storage
    public String imageUrl;

    // Time the ticket was created
    public long timestamp;

    /**
     * Required empty constructor for Firebase Realtime Database.
     * Firebase uses this to deserialize data from the cloud into this Java object.
     */
    public SupportTicket() {
    }

    /**
     * Primary constructor to initialize a new support ticket.
     * * @param ticketId       Unique ID for the ticket
     * @param doctorName     The person submitting the ticket
     * @param category       Issue category
     * @param description    The issue details
     * @param deviceModel    Manufacturer and model of the phone
     * @param androidVersion The OS version of the device
     * @param appVersion     The specific build version of DocConnect
     * @param imageUrl       URL to an attached image (if any)
     */
    public SupportTicket(String ticketId, String doctorName, String category, String description,
                         String deviceModel, String androidVersion, String appVersion, String imageUrl) {
        this.ticketId = ticketId;
        this.doctorName = doctorName;
        this.category = category;
        this.description = description;
        this.deviceModel = deviceModel;
        this.androidVersion = androidVersion;
        this.appVersion = appVersion;
        this.imageUrl = imageUrl;
        // Automatically set the timestamp to the current system time in milliseconds
        this.timestamp = System.currentTimeMillis();
    }
}